# Generated by Django 3.0.7 on 2020-06-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDeshboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('offer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Deshsboard data',
                'verbose_name_plural': 'Deshsboard data',
            },
        ),
    ]
